// src/wallet/dto/create-transaction.dto.ts
import { IsEnum, IsInt, IsNotEmpty, IsOptional, IsPositive, IsString } from 'class-validator';
import { TransactionType } from '../schemas/transaction.schema';

export class CreateTransactionDto {
  @IsEnum(TransactionType)
  type: TransactionType;

  // amount in kobo
  @IsInt()
  @IsPositive()
  amount_kobo: number;

  // unique reference generated by client/server (for idempotency)
  @IsString()
  @IsNotEmpty()
  reference: string;

  // @IsOptional()
  // description: string;

  @IsOptional()
  metadata?: Record<string, any>;
}
